### ISSUE TITLE
Erstellen von der Benutzerverwaltung

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnixAdminTool#1]

**Comment by BroderPeters** [comment]
Additional Feature?:
Beim Löschen eines users auch dessen dateien außerhalb des nutzerverzeichnisses löschen.

**Comment by jmattheis** [comment]
Erstmal alle grundfeatures machen (:

**Comment by BroderPeters** [comment]
Sammle nur Ideen die mir währenddessen einfallen.

**Comment by BroderPeters** [comment]
Bidde checken: 8533bbd
