### ISSUE TITLE
Handbuch

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnixAdminTool#11]
Das Handbuch soll folgendes enthalten:
- Funktionen
- Bedienung
  - Ein einem Beispiel aufzeigen wie man navigiert

**Comment by BroderPeters** [comment]
Handbuch sollte in das Tool miteingebaut werden:
Die entsprechenden Kapitel können in den Bereichen aufgerufen werden und eine gesamt Doku im Hauptmenü.

**Comment by jmattheis** [comment]
jain, halb ja aber soll auch ohne das tool möglich sein, das wir da bilder haben usw

**Comment by BroderPeters** [comment]
Klar, meinte additional

**Comment by BroderPeters** [comment]
Das Handbuch soll folgendes enthalten:
- Kurze Einführung
- Funktionen
- Bedienung
  - Ein einem Beispiel aufzeigen wie man navigiert
- Systemvorraussetzungen?
