### ISSUE TITLE
Toolbezeichnungen

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/UnixAdminTool#12]
Mir fiel soeben auf, dass die Bezeichnung, wie sie im Hauptmenü ('admin.sh') festgelegt wurden, in den einzelnen Modulen abweichen. Zum Beispiel 'Datensicherung' --> 'Backupverwaltung'
Diese gilt es zu bereinigen.

![bildschirmfoto vom 2016-06-22 23 43 19](https://cloud.githubusercontent.com/assets/5406341/16285063/8f66290a-38d4-11e6-9847-7253ec38aae9.png)

**Comment by jmattheis** [comment]
- Datensicherung in Backupverwaltung umbenannt da Datensicherungsverwaltung zulang war (:
- in Packagemgmt exit auf x gepackt
- in admin.sh something special entfernt

Sonst noch irgendwas?

**Comment by BroderPeters** [comment]
An sich alle Punkte die zwischen deinen und meinen Bereichen ungleich sind.
Fallen mir nachher vielleicht noch auf.
