### ISSUE TITLE
Erstellen von der Hardwareverwaltung

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnixAdminTool#6]

**Comment by BroderPeters** [comment]
@jmattheis Falls nicht mehr vorhanden bitte nach Gedächtnis zu erfüllende Punkte hier aufführen.
Habe gerade gar kein Plan mehr

Edit: Abgesehen von 'mount'

**Comment by BroderPeters** [comment]
Leistungsüberwachung (Arbeitsspeicher, CPU), Speicherplatz (frei, belegt)

**Comment by BroderPeters** [comment]
Notizen:
- uptime (Standardmäßig eingeblendet)
- iostat (Input/Output Perfomance Messung)
- vmstat (tabellarische Auskunft über Prozesse, RAM, Auslagerung und Festplatten und Prozessoraktivitäten)
- netstat (Network reporting)
- Verweis auf Processmgmt, da Auslastungen dort festgestellt werden können
- ping
- netstat -i (Netzwerk-Schnittstellendiagnose)
