### ISSUE TITLE
Erstellen von der Cronjobverwaltung

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnixAdminTool#7]

**Comment by BroderPeters** [comment]
_Aufzeichnungen dienen der Struktur für den Assignee_

Cronjobs basieren auf `crontab` in Unix
Alle Crontabs zeigen
Crontab öffnen (nur lesen)
Crontab erstellen
Crontab ändern
Crontab löschen

Alle übrigen Infos, wie zb ein Crontab aussehen kann kommen in die Doku

BTW @jmattheis gibts eigentlich einen Shortcut um das Kommentar direkt zu posten?

**Comment by jmattheis** [comment]
jep `STRG` + `Enter`

**Comment by BroderPeters** [comment]
nice
