### ISSUE TITLE
Erstellen von Somethings Special (:

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnixAdminTool#8]

**Comment by BroderPeters** [comment]
Passiert das hier noch?
Sehe das eher zeitkrititisch nicht machbar.

**Comment by jmattheis** [comment]
closed, da unnötig und zuwenig Zeit (:

**Comment by BroderPeters** [comment]
Wie kannst du da lächeln?! Wir wollten die CD Laufwerke verrückt spielen lassen!
