### ISSUE TITLE
[Allgemeines] Dateien strukturell und logisch ordnen

### ISSUE THREAD

**Issue by 2coiNz** [jmattheis/UnixAdminTool#9]
### Strukturiert euren Code etwas anders!

In dem Moment, wo ihr eigene Funktionen zusammenbaut und diese über ein Menü aufrufen wollt, müssen diese im Programmcode weiter vorne aufgeführt werden. (siehe [usermgnt.sh](https://github.com/jmattheis/UnixAdminTool/blob/master/usermgmt.sh))

Das lässt sich dadurch ändern, dass ihr eure "Main"-Funktion in eine eigene Funktion kapselt und am Dokumentende aufruft. So könnt ihr in jedem Dokument die Struktur beibehalten und macht es demnach besser wart- und steuerbar.

**Ein kleines Beispiel**

```
#!/bin/bash

function main_menu() {
   echo "1 - Zeige alle System-Benutzer"
   read -n 1 -p "Eingabe: " a
   if [ $a -eq 1 ]; then
      userView
   else
      exit 0;
   fi
}

function show_all_users() {
   echo "Alle System-Benutzer --------------------"
   for user in `cat /etc/passwd | cut -d: -f1`; do
      echo $user
   done
}

function userView() {
   show_all_users
}

main_menu
```

By the way: Ich bins - Basti :laughing:

**Comment by jmattheis** [comment]
Gut zu wissen :)

**Comment by BroderPeters** [comment]
Nächstes Mal (;
